Performance improvement
kanselarij-vlaanderen/yggdrasil pull request #29
Opened 2022-01-25 10:26 UTC by erikap

PR covert alle Yggdrasil gerelateerde Jira tickets. Enkel de documentatie in README wordt later nog toegevoegd in KAS-3117.

Propagatie gebeurt steeds op het niveau van agenda's. Data wordt per profiel eerst in een temp-graph verzamelt. Op het  einde wordt de data uit de temp-graph gekopieerd naar de target-graph. Er loopt steeds maar 1 propagatie tegelijk. Alle nieuwe inkomende delta's worden in een cache bijgehouden en verwerkt nadat de vorige propagatie afgerond is.

**High-level flow**
De flow voor inkomende delta messages:
1. inkomende delta's reduceren tot lijst van unieke subjects/objects ([delta-handling.js](https://github.com/kanselarij-vlaanderen/yggdrasil/blob/feature/KAS-2299-improve-performance/repository/delta-handling.js))
2. voor elk van de subjects/objects bepalen tot welke agenda's ze gerelateerd zijn. Voor ieder resource type zijn de mogelijke paden tot een agenda gedefinieerd in [model.js](https://github.com/kanselarij-vlaanderen/yggdrasil/blob/feature/KAS-2299-improve-performance/model.js).
3. voor elk profiel wordt er een [distribution](https://github.com/kanselarij-vlaanderen/yggdrasil/blob/feature/KAS-2299-improve-performance/repository/distributor.js#L21) uitgevoerd voor de geselecteerde agenda's in volgende stappen:
    1. [verzamelen (= collecten)](https://github.com/kanselarij-vlaanderen/yggdrasil/blob/feature/KAS-2299-improve-performance/repository/distributor.js#L30) van de URIs van alle resources die gerelateerd zijn aan een van de agenda's (vergadering, procedurestappen, agenderingen, documenten, nieuwsberichten, ...) in de temp-graph. Afhankelijk van het profiel wordt hierbij rekening gehouden met vrijgave van documenten/beslissingen/nieuwsberichten en het vertrouwelijkheid/toegangsniveau van een document. Voor iedere resource wordt met een triple `?resource ext:tracesLineageTo ?agenda` bijgehouden tot welke agenda's hij relateert (dat kan er meer dan 1 zijn).
    2. voor alle verzamelde URIs in de temp-graph worden [de details gekopieerd](https://github.com/kanselarij-vlaanderen/yggdrasil/blob/feature/KAS-2299-improve-performance/repository/distributor.js#L34). Dwz. alle inkomende en uitgaande triples. In deze stap wordt geen rekening meer gehouden met zichtbaarheid. Als een resource niet beschikbaar mag zijn voor een bepaald profiel is die eruit gefilterd in de vorige stap.
    3. [opkuisen](https://github.com/kanselarij-vlaanderen/yggdrasil/blob/feature/KAS-2299-improve-performance/repository/distributor.js#L39) van gepubliceerde data die niet langer meer zichtbaar mag zijn in de target graph
    4. [kopiëren van data](https://github.com/kanselarij-vlaanderen/yggdrasil/blob/feature/KAS-2299-improve-performance/repository/distributor.js#L44) uit de temp graph naar de target graph. Hier worden enkel triples gekopieerd die effectief verschillend zijn.
    5. [verwijderen van de temp-graph](https://github.com/kanselarij-vlaanderen/yggdrasil/blob/feature/KAS-2299-improve-performance/repository/distributor.js#L54)

**Performantie verbeteringen**
De grootste verschillen met de vorige versie van Yggie, die ook resulteren in een betere performantie, zijn:
- verzamelen/kopiëren van data gebeurt altijd in kleine batches. Ongeacht de grootte van een agenda gaan de queries de database nooit overbelasten. De kleine queries duren ook nooit lang, waardoor de som van veel kleine queries lager is dan de uitvoeringstijd van een grote query.
- het samenstellen van alle data in de temp-graph gebeurt door queries rechtstreeks op Virtuoso i.p.v. via mu-authorization. In de delta-messages hiervan is niemand geinteresseerd.
- bij het kopiëren van data van de temp-graph naar de target-graph worden enkel [de effectief nieuwe triples](https://github.com/kanselarij-vlaanderen/yggdrasil/blob/feature/KAS-2299-improve-performance/repository/distributor.js#L347-L351) gekopieerd. Dit leidt tot veel minder `INSERT DATA` queries naar mu-authorization en bijgevolg ook veel minder delta's waarop mu-search en mu-cl-resources beginnen reageren. Dit heeft een enorme impact op de totale load van het systeem.

**Initiële propagatie**
De flow van de initiele propagatie is gelijkaardig aan die van de delta's, maar dan voor alle agenda's i.p.v. maar een subset van de agenda's. De initiele propagatie van data kan geenabled worden aan de hand van de `RELOAD_ON_INIT` env var.

In dat geval kan ook best de `USE_DIRECT_QUERIES` env var enabled worden. Die zorgt ervoor dat bij het kopiëren van de data van de temp-graph naar de target graph een `COPY <temp-graph> TO <target-graph>` graph operation rechtstreeks op Virtuoso uitgevoerd wordt i.p.v. in batches met SPARQL queries te kopiëren via mu-authorization wat vele malen efficiënter is voor zo'n hoeveelheid data (+- 11M triples per graph). Bij de initiele propagatie is immers niemand geinteresseerd in de delta messages die gegenereerd worden. 

**Data collection**
Het verzamelen van data in de temp graph gebeurt door de [collectors](https://github.com/kanselarij-vlaanderen/yggdrasil/tree/0699f598bed05bf59610e494ee497fcb040670a5/repository/collectors) op basis van de configuratie van de [distributor](https://github.com/kanselarij-vlaanderen/yggdrasil/tree/feature/KAS-2299-improve-performance/repository/distributors), die verschillend is per profiel (vb. overheid mag beslissingen pas zien na de vrijgave van de beslissingen, terwijl een minister die wel onmiddellijk mag zien).

Ik heb zoveel mogelijk inline code documentatie bij de methodes proberen te zetten zodat het duidelijk is wat een methode doet (of met opzet niet doet).

Ik heb geprobeerd consequent te zijn in de naamgeving van de methodes van de collectors:
- _collect**Released**....()_ wil zeggen dat er mogelijks (= afhankelijk van het profiel) een vrijgave van de resource in rekening gebracht wordt 
- _collect**Visible**....()_ wil zeggen dat de zichtbaarheid per profiel afhankelijk is van vertrouwelijkheid/toegangsniveau
- _collect....()_ wil zeggen dat steeds dezelfde data gekopieerd wordt, onafhankelijk van het profiel 

**Benchmarks**
Enkele benchmarks uitgevoerd met deze branch op een replica van productie:
- initiële propagatie: 32 min
- agenda van 18/12/2020 met 184 agendapunten:
    - document permissie aanpassen op afgesloten agenda: 1.48 min
    - agenda heropenen: 2.48 min
    - ontwerpagenda goedkeuren: 3.63 min
- agenda van 4/12/2020 met 80 agendapunten:
    - document permissie aanpassen op afgesloten agenda: 1.18 min
    - agenda heropenen: 2.42 min
    - ontwerpagenda goedkeuren: 2.23 min
- procedurestap in dossier vertrouwelijk maken: 1.32 min 

**Als je zelf wil testen is het belangrijk om eerst een initiële propagatie te laten lopen om van een clean state te vertrekken.**

2022-01-27 15:32 UTC, ValenberghsSven requested changes
Ik merk wat ander gedrag in deze PR.

Ik ben hier grondig naar aan het kijken, maar ga al even tussentijds een review plaatsen omdat ik iets heb gevonden dat mogelijk fout is. (Het meeste van de comments in deze review zijn eerder vragen)
Mogelijk vind ik verderop nog iets en doe ik een nieuwe review

Beslissingen vrijgeven zou voor intern-overheid de beslissingsfiche moeten vrijgeven, maar dat gebeurt niet (de propagatie spec faalt erop)
Die relatie `besluitvorming:genereertVerslag` zit in `collectReleasedDocuments`, die fiche zou moeten gereleased worden op basis van vrijgave beslissingen en niet vrijgave documenten (tenzij dit veranderd is in de business)

2022-01-27 15:32 UTC, ValenberghsSven commented on repository/collectors/decision-collection.js
> +    releaseDateFilter = '?agenda besluitvorming:isAgendaVoor / ext:heeftMailCampagnes / ext:isVerstuurdOp ?sentMailDate .';
We checken hier op het versturen van de effectieve mailchimp campagne en niet de "releasedDecisions" flag op meeting?
Ik weet dat er in het verleden al eens iets fout gegaan is en dat sommige oudere mailcampagnes geen "sendDate" hebben.
Dus mogelijk gaan er enkele agenda's dan geen KB-items hebben.
Ook ga je geen mailchamp campagne hebben voor mededelingen-only agenda's (1tje gehad enkele maanden terug) of andere agenda's zonder mailcampagne (EP, BM)
Die gaat dan ook uit de boot vallen denk ik, en het kort bestek gaat niet te zien zijn?

2022-01-28 12:02 UTC, ValenberghsSven commented on app.js
> +  hasTimeout = true;
timeout verlaagd naar 1 seconde ofzo,
Infinite loop keeps looping

![image](https://user-images.githubusercontent.com/22245223/151543651-47596919-b018-401e-b71d-443d8b2bd3af.png)

2022-01-28 14:38 UTC, ValenberghsSven commented on app.js
> +  hasTimeout = true;
De delta verwerking met deze code:
1e delta komt binnen, we starten een timeout van 60 seconden (default).
Tijdens die 60 seconden komen er nog enkele deltas binnen (want 1 save geeft meestal meerdere deltas)
Pas na die 60 seconden begint de verwerking van de huidige deltas in cache.

Eerste stap in verwerking is die cache lijst clearen, kijken of er een agenda gelinkt is/inzit.
Agenda gevonden betekent propagatie start.
Terwijl de propagatie bezig is zullen alle volgende deltas worden gepush in die cache, en door die timeout checken we elke 60 seconden of we terug kunnen beginnen.
Tot daar ok (in dat geval is de initiële timeout van 60 seconden nog ok, zo zijn we zeker dat we een hoop deltas hebben voor we starten)

Als de cache met delta's leeg is, blijven we in die lus van de timeout.
In het geval van een lege cache zouden we eerder uit de timeout lus moeten springen denk ik zodat de service snachts niet constant zijn delta cache aan het checken is.

De timeout van 60 seconden ligt niet vast, als we die ooit aanpassen met env properties is de tijd van "save" tot effectieve propagatie start mogelijk langer of korter. Daar is iets waar we rekening mee moeten houden tijdens testen.

Op zich kan ik wel leven met die lus hoor, ik wou maar even een gesprek erover starten.

2022-01-28 15:08 UTC, ValenberghsSven commented on repository/delta-cache.js
> +    return cachedArray;
Hier geef je de referentie door van de array ipv een copy, en daarna ga je van `this.cache` een nieuwe lijst maken door die toewijzing naar `[ ]`.

Gaan we hier ooit referentie problemen op hebben? vb push op een array verdwijnt omdat we de array weggooien.
Mogelijk beter de array splicen zodat we echt een "currentState" hebben van de cache en dan ineens de lijst zo leegmaken zonder van `this.cache` een nieuwe lijst te maken?

2022-01-28 15:37 UTC, ValenberghsSven commented on repository/delta-cache.js
> +    return cachedArray;
Ik heb lokaal geprobeerd om iets stuk te krijgen, maar beide methoden (jouwe en mijne oneliner) lijken de deltas correct af te handelen, niet direct iets te zien van mogelijk verdwijende deltas.
Ik vermoed omdat de tijd tussen `const cachedArray = this.cache;` en `this.cache = [];` zo kort is + zelfs als je pushed op ` this.cache` ga je ook pushen op `cachedArray` tot dat die  `this.cache = [];` gelopen heeft.

2022-01-30 19:04 UTC, erikap commented on model.js
> +// TODO refactor collectors to make use of this model configuration to construct query paths
Toekomstig werk. Het nadeel nu is dat als het model wijzigt je eraan moet denken om zowel `model.js` te updaten als de relevante SPARQL queries in de collectors.

2022-01-30 19:06 UTC, erikap commented on .drone.yml
> +    repo: ${DRONE_REPO_NAMESPACE/kanselarij-vlaanderen/kanselarij}/${DRONE_REPO_NAME}
Nee, is hier niet nodig. Dat moet enkel gebeuren indien de repository name op Github niet dezelfde is als de image name op Docker Hub (vb. `kaleidos-frontend` op Github vs `frontend-kaleidos` op Docker Hub). Voor deze service is op het beide plaatsen `yggdrasil` dus de replacement is niet nodig.

2022-01-30 19:07 UTC, erikap commented on Dockerfile
> +FROM semtech/mu-javascript-template:1.5.0-beta.4
Dat is de laatste tagged release van de mu-javascript-template, dus voorlopig wel.

2022-01-30 19:08 UTC, erikap commented on Dockerfile
> +ENV LOG_SPARQL_ALL="false"
Dat was de default configuratie voor de environment variables. Ik heb ze nu verhuisd naar `config.js` zodat het allemaal bij elkaar staat. Dat is inderdaad duidelijker.

2022-01-30 19:09 UTC, erikap commented on model.js
> +  document: [
Ik heb aangepast naar `piece`. Is inderdaad consistenter.

2022-01-30 19:12 UTC, erikap commented on repository/auth-sudo.js
> +}
Omdat `query` en `update` de interface is die we willen aanbieden aan de developer. Dat die onderliggend momenteel hetzelfde zijn, daar moet de developer zich niets van aantrekken. Als we op termijn de updates op een andere manier zouden gaan doen (vb. ander soort HTTP request), kan de implementatie hier verschillend gemaakt worden, zonder alle queries in de service te moeten overlopen/aanpassen.

2022-01-30 19:14 UTC, erikap commented on repository/collectors/agenda-collection.js
> +                  ext:tracesLineageTo ?agenda .
Ja, dat klopt. Is voornamelijk voor consistentie zodat alle resources in de temp-graph een `tracesLineageTo` hebben. Dat was in de vorige versie ook zo en is nu overgenomen. Ik durf momenteel niet met zekerheid zeggen dat het echt noodzakelijk is voor de juiste werking.

2022-01-30 19:18 UTC, erikap commented on app.js
> +  hasTimeout = true;
Die 60 seconden is inderdaad met opzet omdat 1 save meestal resulteert in meerdere delta's en alle delta's dan mee te nemen in 1 Yggie run. Aangezien de doorlooptijd van 1 run nu drastisch gedaald is, kan die 60 seconden misschien ook wel geredureerd worden.

Ik heb de infinite loop er nu uitgehaald zoals je voorstelde. Als er een run afgelopen is, wordt de volgende onmiddellijk gestart als er iets in de delta-cache zit. In het andere geval gebeurt er niets meer en wordt een nieuwe run gescheduled bij het ontvangen van een nieuwe delta. Die zal dan 60s later starten.

2022-01-30 19:18 UTC, erikap commented on repository/collectors/decision-collection.js
> +    releaseDateFilter = '?agenda besluitvorming:isAgendaVoor / ext:heeftMailCampagnes / ext:isVerstuurdOp ?sentMailDate .';
In de vorige versie werd op allebei gecheckt (https://github.com/kanselarij-vlaanderen/yggdrasil/blob/462732ac96002b80022657ae0142cb0e43a37fd5/repository/helpers.js#L865-L866), dus ik heb dat nu ook zo in deze versie gedaan.

2022-01-30 19:19 UTC, erikap commented on repository/delta-cache.js
> +    return cachedArray;
Lijkt me inderdaad geen issue aangezien javascript single-threaded is. Maar ik heb het aangepast naar de one-liner die je voorstelde.

2022-01-31 16:27 UTC, ValenberghsSven requested changes
Ik denk dat ik er grotendeels door ben.
Nog enkele aanpassingen nodig + opmerkingen

Manuele testen + data bekijken moeten we zeker grondig doen op ACC.
Vertrouwelijk lijkt in orde que code, maar ik test gretig mee als het op DEV of ACC staat (bestaande data checken na rebuild is veel sneller dan zelf tig agendas moeten maken)

2022-01-31 16:27 UTC, ValenberghsSven commented on repository/distributors/minister-distributor.js
> +        }
Ik heb gelijkaardige code regelmatig tegengekomen en zat in de oude yggie ook.
Als we gaan querien op de tempgraph, is het dan nog nodig om te checken op lineage?

Ik vermoed dat wij in dit geval zelf alle `dossier:Stuk` hebben toegevoegd aan de tempgraph, en elke toevoeging van dossier:Stuk heeft normaal die lineage dus dient het eerder als een controle.
Hebben we een mogelijk performantie winst als we die check weglaten?
Is dit meer dan een check? komen er pieces in onze tempgraph dat geen lineage hebben met agenda?

2022-01-31 16:27 UTC, ValenberghsSven commented on repository/collectors/document-collection.js
> +    { type: 'besluit:BehandelingVanAgendapunt', predicate: 'besluitvorming:genereertVerslag' },
Dit kwam volgens mij vroeger uit de `fill-intern-overheid.js` extra filter die we meegaven.
```
await runStage('documents added', queryEnv, () => {
      return addAllVisibleRelatedDocuments(queryEnv, `
        { {
          ?agenda (besluitvorming:isAgendaVoor / ext:releasedDocuments) ?date .
          } UNION {
          ?target (ext:zittingDocumentversie | besluitvorming:genereertVerslag)  ?s .
        } }
      `);
```
Als ik de query + filter goed snap, gingen we dus alle documenten enkel meesturen als de "releaseDocuments" triple er was, maar door die union gingen we sowieso die 
`ext:zittingDocumentversie | besluitvorming:genereertVerslag` relaties meepakken (docs van de vergadering &  beslissingsfiches).
Die `?target` matchen dan met treatments omdat de treatments eerder in de tempgraph worden gestoken op basis van de "releasedDecisions" triple

2022-01-31 16:27 UTC, ValenberghsSven commented on repository/distributors/government-distributor.js
> +          }
Correctie, in de oude yggie was er geen lek, omdat daar een fitler op zat:
```
const addAllVisibleRelatedDocuments = async (queryEnv, extraFilters = "") => {
  return addAllRelatedDocuments(queryEnv, `
      ?s <http://mu.semte.ch/vocabularies/ext/toegangsniveauVoorDocumentVersie> ?anyAccessLevel .

      ${extraFilters}
`);
};
```
Die `?anyAccessLevel` zorgde ervoor dat je altijd op zen minste een niveau moet hebben.
Ik zie niets gelijkaardig in de huidige yggie dus mogelijk gaan we een lek creëren met deze

2022-01-31 16:39 UTC, ValenberghsSven commented on repository/collectors/decision-collection.js
> +    releaseDateFilter = '?agenda besluitvorming:isAgendaVoor / ext:heeftMailCampagnes / ext:isVerstuurdOp ?sentMailDate .';
hmm idd, stond al zo.
Maar toch,

220 meetings met releasedDecisions en geen mailchimp (vooral legacy, maar ook recentere agendas)
Met de business checken of die zichtbaar moeten zijn (kan vervolg story, was al zo)
```
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

select count(*) WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/kanselarij> {
    ?session ext:releasedDecisions ?date .
    FILTER NOT EXISTS {
      ?session ext:heeftMailCampagnes / ext:isVerstuurdOp ?sentMailDate .
    }
  }}
```

2022-02-01 22:17 UTC, erikap commented on repository/delta-handling.js
> +      PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
Correct. Ik heb ze verwijderd.

2022-02-01 22:18 UTC, erikap commented on repository/triplestore.js
> +      throw ex;
try-catch toegevoegd rond de `cleanupTempGraphs` want het maakt niet zo veel uit als dat faalt, maar de service mag daar zeker niet op crashen :+1:

2022-02-01 22:20 UTC, erikap commented on repository/yggdrasil.js
> +      'public': new PublicDistributor()
De bedoeling en werking van die `PublicClass` is mij ook niet helemaal duidelijk. Een aparte story om eens uit te zoeken of daar nu effectief nog iets mee gebeurt / noodzakelijk is, is waarschijnlijk een goed idee.

2022-02-01 22:22 UTC, erikap commented on repository/delta-handling.js
> +        PREFIX dossier: <https://data.vlaanderen.be/ns/dossier#>
Inderdaad. Goed gezien. Ik insert ze nu in de query via de model-cache vanuit `model.js`.

2022-02-01 22:24 UTC, erikap commented on repository/distributors/government-distributor.js
> +          }
Nice catch :open_mouth:  Ik heb de query aangepast zodat het bestaan van access-level afgedwongen wordt en er een comment bijgezet waarom het zo moet.

          ?piece ext:file ?file ;
                 ext:toegangsniveauVoorDocumentVersie ?accessLevel .
          FILTER( ?accessLevel != <${ACCESS_LEVEL_CABINET}> )

2022-02-01 22:27 UTC, erikap commented on repository/distributors/minister-distributor.js
> +        }
Die `ext:tracesLineageTo ?agenda` zit vooral in de `WHERE`-clause omdat we die nodig hebben in de `INSERT`-clause van die query. Niet zozeer als extra filter. In de temp-graph moeten we van elke resource weten naar welke agenda's (in scope van de Yggie run) dat die lineage heeft om in de cleanup step de juiste dingen te kunnen verwijderen uit de reeds gepubliceerde data.

2022-02-02 09:20 UTC, ValenberghsSven commented on repository/distributors/minister-distributor.js
> +        }
ja inderdaad daar heb je dat voor nodig, hersenspinsels van mijn kant. :D

2022-02-02 12:09 UTC, ValenberghsSven commented on repository/collectors/agenda-collection.js
> + * a new agenda version will be created.
Agenda actie "Vorige versie heropenen" gaat wel de status aanpassen van een "Approved" agenda naar een "Design" agenda. Niet zeker hoevaak dit in de praktijk gebruikt wordt aangezien het enkel voor noodgevallen zou mogen dienen

2022-02-02 12:25 UTC, erikap commented on repository/collectors/decision-collection.js
> +    releaseDateFilter = '?agenda besluitvorming:isAgendaVoor / ext:heeftMailCampagnes / ext:isVerstuurdOp ?sentMailDate .';
Ik heb een ticket gemaakt (KAS-3143) om uit te klaren met Johan/business wat het moet zijn. Ik vermoed dat je gelijk hebt dat het enkel `ext:releasedDecisions` moet zijn, maar ik zou deze PR daar inderdaad niet op laten blokkeren.

2022-02-02 12:34 UTC, erikap commented on repository/collectors/document-collection.js
> +    { type: 'besluit:BehandelingVanAgendapunt', predicate: 'besluitvorming:genereertVerslag' },
Je interpretatie van die `UNION` lijkt mij correct.

Begrijp ik jou dan correct dat er om de documenten te verzamelen dus 3 soorten checks zijn?
1. documenten die vrijgegeven worden als `releasedDocuments` flag gezet is. Dat is het huidige lijstje zonder `besluitvorming:genereertVerslag`)
2. documenten die vrijgegeven worden als `releasedDecisions` flag gezet is (nl. `besluitvorming:genereertVerslag`)
3. documenten die altijd zichtbaar zijn. Daar is het huidige lijstje correct.

En dan stel je voor om die check in een aparte functie te stekken omdat we die zowel in `document-collection` als `decision-collection` nodig hebben?

2022-02-02 12:38 UTC, ValenberghsSven commented on repository/collectors/decision-collection.js
> +    releaseDateFilter = '?agenda besluitvorming:isAgendaVoor / ext:heeftMailCampagnes / ext:isVerstuurdOp ?sentMailDate .';
:+1:

2022-02-02 12:39 UTC, ValenberghsSven commented on repository/yggdrasil.js
> +      'public': new PublicDistributor()
:+1:

2022-02-02 12:39 UTC, ValenberghsSven commented on repository/distributors/government-distributor.js
> +          }
:+1:

2022-02-02 12:41 UTC, erikap commented on repository/helpers.js
> -
Ik heb een ticket gemaakt (KAS-3144) met de vraag voor Johan/business. Ik zou de PR hier niet op laten blokkeren.

2022-02-02 12:43 UTC, ValenberghsSven commented on repository/collectors/agenda-collection.js
> + * a new agenda version will be created.
We kunnen op ACC testen wat het gevolg is van een "vorige versie heropenen" actie en eventueel nog wat bijstellen als de opkuis niet goed werkt in dat geval.
"als" het in prod gebruikt wordt gaan ze kort daarna terug goedkeuren normaal, dus zou die korte tijd ertussen niet zo erg mogen zijn denk ik.

2022-02-02 12:45 UTC, erikap commented on repository/collectors/agenda-collection.js
> + * a new agenda version will be created.
Ah, die actie kende ik niet. Ik zal de comment aanpassen. Het uitwerken van wat Yggie in dat geval moet doen, lijkt mij sowieso een nieuwe story die in de vorige versie ook nog niet ondersteund is. De prioriteit zal dan afhankelijk zijn van hoe vaak dat effectief in de praktijk gebruikt wordt.
Dat is dan voor het noodgeval waarbij ze per ongeluk de agenda goedgekeurd hebben? Want om wijzigingen aan documenten etc. te doen moeten ze de agenda niet per se heropenen, correct?

2022-02-02 12:58 UTC, ValenberghsSven commented on repository/collectors/document-collection.js
> +    { type: 'besluit:BehandelingVanAgendapunt', predicate: 'besluitvorming:genereertVerslag' },
Je 3 punten kloppen.
aparte functie had ik geopperd, maar punt 1 en 3 zitten al samen onder de functie `collectReleasedDocuments`
punt 2 is eigenlijk dan een kopie van punt 1 met andere paths en filter. Kan wel samen in dezelfde functie dan zit alles qua documenten samen

2022-02-02 13:14 UTC, ValenberghsSven commented on repository/helpers.js
> -
Dit mag de release niet tegenhouden aangezien het ook al zo was op vorige yggie

2022-02-02 13:52 UTC, erikap commented on repository/collectors/document-collection.js
> +    { type: 'besluit:BehandelingVanAgendapunt', predicate: 'besluitvorming:genereertVerslag' },
Ok, aangepast. De SPARQL filters zitten nu in een aparte file `repository/collectors/release-validations.js`, want ik had de filter van released-newsitems bijvoorbeeld al maar op 1 plaats gecorrigeerd terwijl die op 2 plaatsen gebruikt werd :see_no_evil:

2022-02-03 13:57 UTC, merged