Add mechanism to filter out triples from temp graph before propagating
kanselarij-vlaanderen/yggdrasil pull request #32
Opened 2022-04-05 08:33 UTC by sergiofenoll

Backend PR: https://github.com/kanselarij-vlaanderen/app-kaleidos/pull/265
Frontend PR: https://github.com/kanselarij-vlaanderen/frontend-kaleidos/pull/1282

Adds filtering for privateComment triples so they don't get propagated to other graphs.

Function doing the filtering runs after all resources have been collected (so after the temp graph is full), then deletes the triples we want to filter out before continuing with propagation.

Filtering function is meant to be somewhat extensible. Currently the filtered out triples are defined in a map per type (so in this case, there's a filter for the type `besluit:Agendapunt`), and filters follow the syntax used by delta notifier resourceFormat v0.0.1.
Multiple filters can be added per type and more types can be added without having to alter the queries themselves. Can't combine filters though (although I doubt we'd need it, but it could be an interesting addition in the future).

Used the same batching technique that is used in the `collectResourceDetails() ` queries in case we end up having to delete a lot of triples.

2022-04-05 09:06 UTC, erikap requested changes
Functionally, this code works :+1:  Comments are mainly for readability and maintainability

2022-04-05 09:06 UTC, erikap commented on repository/distributor.js
> +            predString = `BIND("""${predicate.value}""" AS ?p) .`;
This case cannot occur for a predicate

2022-04-05 09:06 UTC, erikap commented on repository/distributor.js
> +          await runStage(`Delete filtered triples of <${type}> (batch ${currentBatch + 1}/${totalBatches})`, async () => {
Can you add the filter to the log message as well, because now we will have the same log message if there are multiple filters for the same type. However, not sure how to elegantly inline that generic filter :thinking: 
May a combo of `runStage` with [`forLoopProgressBar`](https://github.com/kanselarij-vlaanderen/yggdrasil/blob/0f45590a17ef4b1866d99ebe99c485544bc2437a/repository/timing.js#L17) works better?

2022-04-05 21:38 UTC, erikap commented on repository/query-helpers.js
> +        SELECT ?s ?p ?o
Did you test this query? `?s`, `?p` and/or `?o` may not be defined in the `WHERE`-clause depending on the params that are passed to `deleteResource`. Or am I missing something here? :thinking:

2022-04-05 21:52 UTC, sergiofenoll commented on repository/query-helpers.js
> +        SELECT ?s ?p ?o
I did, and I got the expected output & didn't get any exceptions, but now that you mention it, I don't think it should work. E.g. for the currently implemented filter, the predicate should be a URI, so `?p` wouldn't be defined, so the query should fail. Going to have a look...

2022-04-05 22:03 UTC, sergiofenoll commented on repository/query-helpers.js
> +        SELECT ?s ?p ?o
it seems that mu-authorization is either coping with the bad query or swallowing an error and just trucking along (because the first outgoing query should fail with the following error: `Virtuoso 37000 Error SP031: SPARQL compiler: Variable 'p' is used in the query result set but not assigned`, but it doesn't and it just goes on to execute the actual `DELETE`)
```
Incoming SPARQL query: 
    DELETE {
      GRAPH <http://mu.semte.ch/graphs/temp/c5af32d0-b52a-11ec-9a27-f990d2258d94> {
        ?s <http://mu.semte.ch/vocabularies/ext/privateComment> ?o .
      }
    }
    WHERE {
      GRAPH <http://mu.semte.ch/graphs/temp/c5af32d0-b52a-11ec-9a27-f990d2258d94> {
        SELECT ?s ?p ?o
          WHERE {
            ?s a <http://data.vlaanderen.be/ns/besluit#Agendapunt> .
            ?s <http://mu.semte.ch/vocabularies/ext/privateComment> ?o .
          }
          LIMIT 2500
      }
    }
  
Received access rights: :sudo
Outgoing SPARQL query: SELECT DISTINCT ?s ?o WHERE 
{
  GRAPH <http://mu.semte.ch/graphs/temp/c5af32d0-b52a-11ec-9a27-f990d2258d94> 
  {
    SELECT ?s ?p ?o WHERE 
    {
      ?s a <http://data.vlaanderen.be/ns/besluit#Agendapunt> .
      ?s <http://mu.semte.ch/vocabularies/ext/privateComment> ?o .
      
    }
    LIMIT  2500 
  }
  
}

Outgoing SPARQL query: DELETE DATA 
{
  GRAPH <http://mu.semte.ch/graphs/temp/c5af32d0-b52a-11ec-9a27-f990d2258d94> 
  {
    <http://themis.vlaanderen.be/id/agendapunt/624CB8883ABC4C117CAC4BB6> <http://mu.semte.ch/vocabularies/ext/privateComment> """casdgsagsdaf""" 
  }
  
}
```
in any case, will edit the query tomorrow

2022-04-06 09:21 UTC, ValenberghsSven commented on repository/query-helpers.js
>        }
Trying to wrap my head around this query.
It looks technically possible to end up with a query that deletes everything in the graph.
```
DELETE ?s ?p ?o {}
Where ?s ?p ?o {}
```
You just have have to call `deleteResource(graph)`.

2022-04-06 09:44 UTC, ValenberghsSven requested changes
The current refactor provides a method that can filter predicates going left or right, making the logic very complex to work both ways.

Could we keep the old method and create a new method for this new edge-case?
Changing the generic simple logic to a more complex one just complicates things.
My proposition would be to make a method where you can delete a subject with a defined predicate.
In my head it would look like half the current deleteResource (don't do the inverse)
With a delete query that just has the predicate.
```
DELETE {
      GRAPH <${graph}> {
         ${sparqlEscapeUri(subject)}  ${sparqlEscapeUri(predicate)} ?o .
        }
      }
```
Since you have the restrictions, you can query the temp DB, grab all the subjects and loop them, passing the subject + the single predicate.
Then you don't need `type` anymore, you already queried what you need.
We can worry later when you need a list of predicates or a list of types with predicates.

2022-04-07 07:10 UTC, sergiofenoll commented
> The current refactor provides a method that can filter predicates going left or right, making the logic very complex to work both ways.
> 
> Could we keep the old method and create a new method for this new edge-case? Changing the generic simple logic to a more complex one just complicates things. My proposition would be to make a method where you can delete a subject with a defined predicate. In my head it would look like half the current deleteResource (don't do the inverse) With a delete query that just has the predicate as an addition.
> 
> ```
> DELETE {
>       GRAPH <${graph}> {
>          ${sparqlEscapeUri(subject)}  ${sparqlEscapeUri(predicate)} ?o .
>         }
>       }
> ```
> 
> Since you have the restrictions, you can query the temp graph (in `filterCollectedDetails`), grab all the subjects and loop them, passing the subject + the single predicate to the new `deleteSubjectWithPredicate` method. (name is just f.e.) Then you don't need `type` anymore, you already queried what you need.
> 
> We can worry later about what should happen if you have a list of predicates of 1 type or a list of types with predicates. We don't need this logic right now.
> 
> You could also just query the full triple and loop them through a delete method.

Agreed that making the `deleteResource` function (which should at that point be called `deleteTriples`) generic makes it somewhat more complex. Will re-add the previous query & make a new one for deleting stuff based on predicate.

I do wonder if querying for subjects, then deleting them one-by-one would be detrimental to the general performance of this service. Because then instead of making 1 request we're making N requests, and we're removing the DBs ability to optimize the DELETE query (if it does that to begin with, but I would assume so). But maybe in practice we're never going to be filtering out so many triples that it becomes a problem.

2022-04-07 08:59 UTC, ValenberghsSven commented
"I do wonder if querying for subjects, then deleting them one-by-one would be detrimental to the general performance of this service. Because then instead of making 1 request we're making N requests, and we're removing the DBs ability to optimize the DELETE query (if it does that to begin with, but I would assume so). But maybe in practice we're never going to be filtering out so many triples that it becomes a problem."

Was not thinking in terms of performance for this one.
The current `deleteResource` is already called one by one right now:
`await forLoopProgressBar(resources, async (resource) => {`

The current cleanup queries are not called often with current implementation. 
With this predicate filtering, we will constantly be calling the queries so we do need to look at performance.
What would be a good solution?
We could send the `resources` list to a delete method, and then batch delete or something.
Perhaps this needs to be discussed in rocket chat or in a call. This back and forth is slowing progress

2022-04-09 09:24 UTC, erikap commented
@sergiofenoll has a valid point that iterating over all resources will have a performance impact, since it will result in a lot more queries being executed.

It only comes to my mind now that it is best not to use the `deleteResource` helper from `query-helpers`. That helper executes queries against mu-authorization, resulting in delta-notifications being sent. Since the cleanup step is manipulating data in the tmp-graph, no one will/should be interested in those deltas. The tmp-graph is considered to be only internal calculation for Yggdrasil. Therefore, the current implementation uses `updateTriplestore` to execute queries against Virtuoso directly when manipulating data in the tmp-graph to avoid useless delta messages being sent (e.g. https://github.com/kanselarij-vlaanderen/yggdrasil/blob/0795ecad1b0648f79a9e68de18467413bb39cbd9/repository/distributor.js#L113).

I agree with @ValenberghsSven that we should maybe not aim for a super-generic solution now since we don't have a clear picture of the future use cases that will land in the cleanup step. For now, I would keep the `filterCollectedDetails`-method, but just define a SPARQL query inline that uses `updateTriplestore` and removes all triples `?s a besluit:Agendapunt ; ext:privateComment ?comment . ` in batches. We can see later how that SPARQL query must evolve when more cleanups need to be executed.

2022-04-09 09:24 UTC, erikap commented
@sergiofenoll has a valid point that iterating over all resources will have a performance impact, since it will result in a lot more queries being executed.

It only comes to my mind now that it is best not to use the `deleteResource` helper from `query-helpers`. That helper executes queries against mu-authorization, resulting in delta-notifications being sent. Since the cleanup step is manipulating data in the tmp-graph, no one will/should be interested in those deltas. The tmp-graph is considered to be only internal calculation for Yggdrasil. Therefore, the current implementation uses `updateTriplestore` to execute queries against Virtuoso directly when manipulating data in the tmp-graph to avoid useless delta messages being sent (e.g. https://github.com/kanselarij-vlaanderen/yggdrasil/blob/0795ecad1b0648f79a9e68de18467413bb39cbd9/repository/distributor.js#L113).

I agree with @ValenberghsSven that we should maybe not aim for a super-generic solution now since we don't have a clear picture of the future use cases that will land in the cleanup step. For now, I would keep the `filterCollectedDetails`-method, but just define a SPARQL query inline that uses `updateTriplestore` and removes all triples `?s a besluit:Agendapunt ; ext:privateComment ?comment . ` in batches. We can see later how that SPARQL query must evolve when more cleanups need to be executed.

2022-04-11 07:45 UTC, erikap requested changes

2022-04-11 07:45 UTC, erikap commented on repository/query-helpers.js
> +  deleteResource,
Must be removed?

2022-04-11 07:45 UTC, erikap commented on repository/distributor.js
> +    const count = await countResources({ graph: this.tempGraph, type: 'http://data.vlaanderen.be/ns/besluit#Agendapunt' });
We're counting all agendaitems here, while they will not all have a triple with `ext:privateComment` (most of them won't) so we will execute the delete query in the while-loop too many times. It will not break the data, since the delete query will just not have any effect, but it's probably better to only count resources of type agendaitem that have `ext:privateComment`?

2022-04-11 08:14 UTC, sergiofenoll commented on repository/query-helpers.js
> +  deleteResource,
Are trailing commas not allowed in exports?

2022-04-11 08:21 UTC, erikap commented on repository/query-helpers.js
> +  deleteResource,
Sorry, misread this one. I thought it was a leftover of previous commit adding a new export that didn't exist anymore. Just ignore this one :slightly_smiling_face:

2022-04-11 18:46 UTC, erikap approved these changes

2022-04-11 18:46 UTC, merged