Feature/kas 3360 aanpassen van vertrouwelijkheidstoggle op document niveau naar extra toegangsniveaus
kanselarij-vlaanderen/yggdrasil pull request #33
Opened 2022-04-29 13:48 UTC by sergiofenoll

Backend PR: https://github.com/kanselarij-vlaanderen/app-kaleidos/pull/275

Only use access level to determine if a piece's visible file should be propagated (confidentiality is no longer a thing for pieces)

2022-05-06 11:36 UTC, erikap requested changes

2022-05-06 11:36 UTC, erikap commented on repository/distributors/minister-distributor.js
> +          FILTER ( ?accessLevel != <${ACCESS_LEVEL_INTERNAL_SECRETARY}> )
Don't forget to update the inline code documentation as well.

2022-05-06 11:36 UTC, erikap commented on constants.js
> +const ACCESS_LEVEL_INTERNAL_SECRETARY = 'http://kanselarij.vo.data.gift/id/concept/toegangs-niveaus/4bbbbc03-5dda-4885-a42f-7ee68fea1aae';
To be in line with the other variables, I would leave out `INTERNAL` and just use `ACCESS_LEVEL_SECRETARY`

2022-05-10 15:14 UTC, ValenberghsSven approved these changes
Tested a bit, seems like we only distribute the files the profiles are supposed to see :+1:

2022-05-17 08:39 UTC, erikap approved these changes

2022-05-17 08:40 UTC, merged