KAS-2742: Updated newsletter model
kanselarij-vlaanderen/yggdrasil pull request #51
Opened 2022-12-07 07:26 UTC by sergiofenoll

Updates the RDF class of news item and the predicate used to get a news item's attachments

2022-12-12 18:25 UTC, erikap requested changes
Changes in relations are still missing in `model.js`
- `ext:documentVoorPublicatie` -> `besluitvorming:heeftBijlage` between `newsitem` and `piece`
-  `prov:generated` -> `^prov:wasDerivedFrom` between `agendaitem-treatment` and `newsitem`

2022-12-13 15:34 UTC, ValenberghsSven commented on model.js
> -  { key: 'newsitem', uri: 'besluitvorming:NieuwsbriefInfo' },
was already here but `newsItem` (capital i) would be more accurate? + line 64 and 72.

2022-12-13 15:37 UTC, ValenberghsSven commented on model.js
> -  { key: 'newsitem', uri: 'besluitvorming:NieuwsbriefInfo' },
not really a big deal, I now see that `agendaitemTreatment` also doesn't match up with the resource `agenda-item-treatment` and would also need a capital i.
Can ignore, not bothered

2022-12-13 15:37 UTC, ValenberghsSven approved these changes

2022-12-13 15:59 UTC, erikap approved these changes

2022-12-14 07:51 UTC, merged